// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stainer.Web.Infrastructure.Data;

#nullable disable

namespace Stainer.Web.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StainerDbContext))]
    [Migration("20260624024739_WorkflowReagentScanModel")]
    partial class WorkflowReagentScanModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Stainer.Web.Domain.Entities.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateCalibrationHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AspirateZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aspirate_z_um");

                    b.Property<string>("CalibratedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("calibrated_by_user_id");

                    b.Property<string>("CoordinatePointId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("coordinate_point_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DispenseZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispense_z_um");

                    b.Property<long?>("NewXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_x_um");

                    b.Property<long?>("NewYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_y_um");

                    b.Property<long?>("PreviousXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_x_um");

                    b.Property<long?>("PreviousYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_y_um");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<long?>("SafeZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("safe_z_um");

                    b.HasKey("Id");

                    b.HasIndex("CalibratedByUserId");

                    b.HasIndex("CoordinatePointId");

                    b.ToTable("coordinate_calibration_history", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinatePoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AspirateZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aspirate_z_um");

                    b.Property<long?>("CalibratedXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("calibrated_x_um");

                    b.Property<long?>("CalibratedYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("calibrated_y_um");

                    b.Property<string>("CoordinateProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("coordinate_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DispenseZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispense_z_um");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("PointCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_code");

                    b.Property<string>("PointType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_type");

                    b.Property<long?>("PresetXUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_x_um");

                    b.Property<long?>("PresetYUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_y_um");

                    b.Property<bool>("RequiresCalibration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_calibration");

                    b.Property<long?>("SafeZUm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("safe_z_um");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateProfileId", "PointCode")
                        .IsUnique();

                    b.ToTable("coordinate_points", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OriginDefinition")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("origin_definition");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("coordinate_profiles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.DabMixPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_no");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PositionNo")
                        .IsUnique();

                    b.ToTable("dab_mix_positions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.DeviceProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("device_profiles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Drawer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("HeatBoardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heat_board_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HeatBoardId")
                        .IsUnique();

                    b.ToTable("drawers", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.LiquidClassProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("AspirateSpeedUlPerSecond")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aspirate_speed_ul_per_second");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DispenseSpeedUlPerSecond")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispense_speed_ul_per_second");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int?>("MixCycles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mix_cycles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PreWetCycles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pre_wet_cycles");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("liquid_class_profiles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.PhysicalSlot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DrawerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("drawer_id");

                    b.Property<int>("HeatPointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heat_point_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<int>("VerticalOrderFromBottom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vertical_order_from_bottom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DrawerId", "HeatPointId")
                        .IsUnique();

                    b.HasIndex("DrawerId", "SlotNo")
                        .IsUnique();

                    b.ToTable("physical_slots", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.PrimaryAntibodyWorkflowMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("PrimaryAntibodyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_antibody_code");

                    b.Property<string>("WorkflowVersionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryAntibodyCode");

                    b.HasIndex("WorkflowVersionId");

                    b.HasIndex("PrimaryAntibodyCode", "WorkflowVersionId")
                        .IsUnique();

                    b.ToTable("primary_antibody_workflow_mappings", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentBottle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<DateTimeOffset?>("FirstScannedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_scanned_at_utc");

                    b.Property<string>("FullBarcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_barcode");

                    b.Property<int>("InitialVolumeUl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_volume_ul");

                    b.Property<DateTimeOffset?>("LastScannedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scanned_at_utc");

                    b.Property<string>("ProductionBatchNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("production_batch_no");

                    b.Property<string>("ReagentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_code");

                    b.Property<string>("ReagentDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_definition_id");

                    b.Property<int>("RemainingVolumeUl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remaining_volume_ul");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("FullBarcode")
                        .IsUnique();

                    b.HasIndex("ReagentDefinitionId");

                    b.HasIndex("ReagentCode", "ProductionBatchNo", "SerialNo")
                        .IsUnique();

                    b.ToTable("reagent_bottles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LiquidClassProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("liquid_class_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ReagentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_code");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LiquidClassProfileId");

                    b.HasIndex("ReagentCode")
                        .IsUnique();

                    b.ToTable("reagent_definitions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentRackPlacement", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("PlacedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("placed_at_utc");

                    b.Property<string>("ReagentBottleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_bottle_id");

                    b.Property<string>("ReagentRackPositionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_rack_position_id");

                    b.Property<string>("ReagentScanSessionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_scan_session_id");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("removed_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ReagentBottleId")
                        .IsUnique()
                        .HasFilter("removed_at_utc IS NULL");

                    b.HasIndex("ReagentRackPositionId")
                        .IsUnique()
                        .HasFilter("removed_at_utc IS NULL");

                    b.HasIndex("ReagentScanSessionId");

                    b.HasIndex("ReagentBottleId", "PlacedAtUtc");

                    b.ToTable("reagent_rack_placements", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentRackPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<int>("ColumnNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("column_no");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_no");

                    b.Property<int>("RowNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_no");

                    b.Property<string>("ScannerChannelCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("scanner_channel_code");

                    b.Property<int>("ScannerChannelNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scanner_channel_no");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PositionNo")
                        .IsUnique();

                    b.HasIndex("ColumnNo", "RowNo")
                        .IsUnique();

                    b.ToTable("reagent_rack_positions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentScanItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsValidationPassed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_validation_passed");

                    b.Property<string>("LocatorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("locator_code");

                    b.Property<string>("ParsedBatchNo")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_batch_no");

                    b.Property<int?>("ParsedQuantityUl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parsed_quantity_ul");

                    b.Property<string>("ParsedReagentCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_reagent_code");

                    b.Property<string>("ParsedSerialNo")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("parsed_serial_no");

                    b.Property<string>("RawBarcode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_barcode");

                    b.Property<string>("ReagentRackPositionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_rack_position_id");

                    b.Property<string>("ReagentScanSessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_scan_session_id");

                    b.Property<string>("ScanResult")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_result");

                    b.Property<string>("ScannerChannelCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("scanner_channel_code");

                    b.Property<int>("ScannerChannelNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scanner_channel_no");

                    b.Property<string>("ValidationMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_message");

                    b.HasKey("Id");

                    b.HasIndex("ParsedReagentCode");

                    b.HasIndex("RawBarcode");

                    b.HasIndex("ReagentRackPositionId");

                    b.HasIndex("ScanResult");

                    b.HasIndex("ReagentScanSessionId", "ReagentRackPositionId")
                        .IsUnique();

                    b.ToTable("reagent_scan_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_reagent_scan_items_scan_result", "scan_result in ('EMPTY', 'VALID', 'INVALID')");
                        });
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentScanSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_code");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("reagent_scan_sessions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WashPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("WashType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("wash_type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("wash_positions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("WorkflowType");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowReagentRequirement", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<string>("ReagentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_code");

                    b.Property<int?>("RequiredVolumeUl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("required_volume_ul");

                    b.Property<string>("WorkflowVersionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id");

                    b.HasIndex("ReagentCode");

                    b.HasIndex("WorkflowVersionId", "ReagentCode")
                        .IsUnique();

                    b.ToTable("workflow_reagent_requirements", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FailureStrategy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_strategy");

                    b.Property<string>("MajorStepCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("major_step_code");

                    b.Property<string>("MixParametersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("mix_parameters_json");

                    b.Property<string>("ReagentCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reagent_code");

                    b.Property<int>("StepNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_no");

                    b.Property<int?>("TargetTemperatureDeciC")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_temperature_deci_c");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int?>("VolumeUl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume_ul");

                    b.Property<string>("WashParametersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("wash_parameters_json");

                    b.Property<string>("WorkflowVersionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id");

                    b.HasIndex("ReagentCode");

                    b.HasIndex("WorkflowVersionId", "StepNo")
                        .IsUnique();

                    b.ToTable("workflow_steps", (string)null);
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("change_note");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at_utc");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("retired_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_no");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId", "VersionNo")
                        .IsUnique();

                    b.ToTable("workflow_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_versions_status", "status in ('Draft', 'Published', 'Retired')");
                        });
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateCalibrationHistory", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.User", "CalibratedByUser")
                        .WithMany()
                        .HasForeignKey("CalibratedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stainer.Web.Domain.Entities.CoordinatePoint", "CoordinatePoint")
                        .WithMany("CalibrationHistory")
                        .HasForeignKey("CoordinatePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalibratedByUser");

                    b.Navigation("CoordinatePoint");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinatePoint", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.CoordinateProfile", "CoordinateProfile")
                        .WithMany("CoordinatePoints")
                        .HasForeignKey("CoordinateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinateProfile");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.PhysicalSlot", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.Drawer", "Drawer")
                        .WithMany("PhysicalSlots")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.PrimaryAntibodyWorkflowMapping", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.WorkflowVersion", "WorkflowVersion")
                        .WithMany("PrimaryAntibodyMappings")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentBottle", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.ReagentDefinition", "ReagentDefinition")
                        .WithMany("Bottles")
                        .HasForeignKey("ReagentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReagentDefinition");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentDefinition", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.LiquidClassProfile", "LiquidClassProfile")
                        .WithMany("ReagentDefinitions")
                        .HasForeignKey("LiquidClassProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LiquidClassProfile");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentRackPlacement", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.ReagentBottle", "ReagentBottle")
                        .WithMany("Placements")
                        .HasForeignKey("ReagentBottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stainer.Web.Domain.Entities.ReagentRackPosition", "ReagentRackPosition")
                        .WithMany()
                        .HasForeignKey("ReagentRackPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stainer.Web.Domain.Entities.ReagentScanSession", "ReagentScanSession")
                        .WithMany("Placements")
                        .HasForeignKey("ReagentScanSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReagentBottle");

                    b.Navigation("ReagentRackPosition");

                    b.Navigation("ReagentScanSession");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentScanItem", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.ReagentRackPosition", "ReagentRackPosition")
                        .WithMany()
                        .HasForeignKey("ReagentRackPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stainer.Web.Domain.Entities.ReagentScanSession", "ReagentScanSession")
                        .WithMany("Items")
                        .HasForeignKey("ReagentScanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReagentRackPosition");

                    b.Navigation("ReagentScanSession");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentScanSession", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stainer.Web.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowReagentRequirement", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.WorkflowVersion", "WorkflowVersion")
                        .WithMany("ReagentRequirements")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.WorkflowVersion", "WorkflowVersion")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowVersion", b =>
                {
                    b.HasOne("Stainer.Web.Domain.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinatePoint", b =>
                {
                    b.Navigation("CalibrationHistory");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.CoordinateProfile", b =>
                {
                    b.Navigation("CoordinatePoints");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Drawer", b =>
                {
                    b.Navigation("PhysicalSlots");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.LiquidClassProfile", b =>
                {
                    b.Navigation("ReagentDefinitions");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentBottle", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentDefinition", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.ReagentScanSession", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Stainer.Web.Domain.Entities.WorkflowVersion", b =>
                {
                    b.Navigation("PrimaryAntibodyMappings");

                    b.Navigation("ReagentRequirements");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
